### ISSUE TITLE
Move to github.com/sugarlabs?

### ISSUE THREAD

**Issue by davelab6** [sugarlabs/level-activity#2]
Perhaps this activity could live within sugarlabs? :)

**Comment by godiard** [comment]
Anybody can clone the repository :)

**Comment by davelab6** [comment]
I think it is bad for the overall sugarlabs project for sugar activities to be scattered all around the web. Do you agree?

**Comment by godiard** [comment]
Is certainly a problem, but if all is in the sugarlabs project, then you need people with administration privileges in the project create repositories for every developer (or give such privileges to everybody).
At least at the time the move to github was done, that was the reason.

**Comment by davelab6** [comment]
We can individually and autonomously initiate the transfer, and the admins can accept it. 

Simply visit https://github.com/godiard/level-activity/settings and at the bottom click the `Transfer` button. 

You can read more in https://help.github.com/articles/transferring-a-repository/ :)
